In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('AviationData.csv', encoding = "ISO-8859-1")

In [3]:
df.head()

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.Flight,Air.Carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.Phase.of.Flight,Report.Status,Publication.Date
0,20200102X82407,Accident,WPR20CA055,2019-12-31,"Elk, CA",United States,39.128611,-123.715833,LLR,Little River,...,Personal,NaN,NaN,NaN,NaN,1.0,VMC,TAKEOFF,Factual,13/01/2020
1,20191231X83852,Accident,CEN20FA049,2019-12-31,"OLATHE, KS",United States,38.846111,-94.736111,OJC,Johnson County Executive,...,Personal,NaN,2.0,NaN,NaN,NaN,VMC,TAKEOFF,Preliminary,08/01/2020
2,20200102X54844,Accident,ANC20CA011,2019-12-31,"Fairbanks, AK",United States,64.666945,-148.133334,NaN,NaN,...,Personal,NaN,NaN,NaN,NaN,2.0,NaN,NaN,Preliminary,02/01/2020
3,20191230X91852,Accident,CEN20CA048,2019-12-30,"GRANBURY, TX",United States,32.365556,-97.645000,NaN,NaN,...,Personal,NaN,NaN,NaN,NaN,1.0,NaN,NaN,Preliminary,31/12/2019
4,20191228X62945,NaN,WPR20CA053,2019-12-28,"Missoula, MT",United States,NaN,NaN,MSO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary,03/01/2020

In [4]:
cols_to_drop = ['Investigation.Type','Accident.Number','Airport.Name','Registration.Number','Amateur.Built',\
               'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.Flight',\
               'Air.Carrier', 'Weather.Condition','Report.Status','Publication.Date']

In [5]:
df.drop(cols_to_drop, 1, inplace=True)

In [6]:
df.head()

,Event.Id,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Injury.Severity,Aircraft.Damage,Aircraft.Category,Make,Model,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Broad.Phase.of.Flight
0,20200102X82407,2019-12-31,"Elk, CA",United States,39.128611,-123.715833,LLR,Non-Fatal,Substantial,Airplane,Cessna,175,NaN,NaN,NaN,1.0,TAKEOFF
1,20191231X83852,2019-12-31,"OLATHE, KS",United States,38.846111,-94.736111,OJC,Fatal(2),Destroyed,Airplane,Mooney,M20S,2.0,NaN,NaN,NaN,TAKEOFF
2,20200102X54844,2019-12-31,"Fairbanks, AK",United States,64.666945,-148.133334,NaN,Non-Fatal,Substantial,Airplane,Cessna,170,NaN,NaN,NaN,2.0,NaN
3,20191230X91852,2019-12-30,"GRANBURY, TX",United States,32.365556,-97.645000,NaN,Non-Fatal,Substantial,Airplane,Vans,RV 10,NaN,NaN,NaN,1.0,NaN
4,20191228X62945,2019-12-28,"Missoula, MT",United States,NaN,NaN,MSO,Unavailable,Substantial,NaN,Cessna,170,NaN,NaN,NaN,NaN,NaN

In [7]:
# fill NaN in injury columns with zeroes as they should be. 

df['Total.Fatal.Injuries'].fillna(0, inplace=True)

In [9]:
df['Total.Serious.Injuries'].fillna(0, inplace=True)
df['Total.Minor.Injuries'].fillna(0, inplace=True)
df['Total.Uninjured'].fillna(0, inplace=True)

In [10]:
df.head()

,Event.Id,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Injury.Severity,Aircraft.Damage,Aircraft.Category,Make,Model,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Broad.Phase.of.Flight
0,20200102X82407,2019-12-31,"Elk, CA",United States,39.128611,-123.715833,LLR,Non-Fatal,Substantial,Airplane,Cessna,175,0.0,0.0,0.0,1.0,TAKEOFF
1,20191231X83852,2019-12-31,"OLATHE, KS",United States,38.846111,-94.736111,OJC,Fatal(2),Destroyed,Airplane,Mooney,M20S,2.0,0.0,0.0,0.0,TAKEOFF
2,20200102X54844,2019-12-31,"Fairbanks, AK",United States,64.666945,-148.133334,NaN,Non-Fatal,Substantial,Airplane,Cessna,170,0.0,0.0,0.0,2.0,NaN
3,20191230X91852,2019-12-30,"GRANBURY, TX",United States,32.365556,-97.645000,NaN,Non-Fatal,Substantial,Airplane,Vans,RV 10,0.0,0.0,0.0,1.0,NaN
4,20191228X62945,2019-12-28,"Missoula, MT",United States,NaN,NaN,MSO,Unavailable,Substantial,NaN,Cessna,170,0.0,0.0,0.0,0.0,NaN

In [11]:
# fill NaN in flight phase with UNKNOWNs. 

df['Broad.Phase.of.Flight'].fillna('UNKNOWN', inplace=True)

In [12]:
df.head()

,Event.Id,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Injury.Severity,Aircraft.Damage,Aircraft.Category,Make,Model,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Broad.Phase.of.Flight
0,20200102X82407,2019-12-31,"Elk, CA",United States,39.128611,-123.715833,LLR,Non-Fatal,Substantial,Airplane,Cessna,175,0.0,0.0,0.0,1.0,TAKEOFF
1,20191231X83852,2019-12-31,"OLATHE, KS",United States,38.846111,-94.736111,OJC,Fatal(2),Destroyed,Airplane,Mooney,M20S,2.0,0.0,0.0,0.0,TAKEOFF
2,20200102X54844,2019-12-31,"Fairbanks, AK",United States,64.666945,-148.133334,NaN,Non-Fatal,Substantial,Airplane,Cessna,170,0.0,0.0,0.0,2.0,UNKNOWN
3,20191230X91852,2019-12-30,"GRANBURY, TX",United States,32.365556,-97.645000,NaN,Non-Fatal,Substantial,Airplane,Vans,RV 10,0.0,0.0,0.0,1.0,UNKNOWN
4,20191228X62945,2019-12-28,"Missoula, MT",United States,NaN,NaN,MSO,Unavailable,Substantial,NaN,Cessna,170,0.0,0.0,0.0,0.0,UNKNOWN

In [13]:
# drop accidents with no coordinates

df.dropna(subset=['Latitude'], inplace=True)

In [14]:
df.head()

,Event.Id,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Injury.Severity,Aircraft.Damage,Aircraft.Category,Make,Model,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Broad.Phase.of.Flight
0,20200102X82407,2019-12-31,"Elk, CA",United States,39.128611,-123.715833,LLR,Non-Fatal,Substantial,Airplane,Cessna,175,0.0,0.0,0.0,1.0,TAKEOFF
1,20191231X83852,2019-12-31,"OLATHE, KS",United States,38.846111,-94.736111,OJC,Fatal(2),Destroyed,Airplane,Mooney,M20S,2.0,0.0,0.0,0.0,TAKEOFF
2,20200102X54844,2019-12-31,"Fairbanks, AK",United States,64.666945,-148.133334,NaN,Non-Fatal,Substantial,Airplane,Cessna,170,0.0,0.0,0.0,2.0,UNKNOWN
3,20191230X91852,2019-12-30,"GRANBURY, TX",United States,32.365556,-97.645000,NaN,Non-Fatal,Substantial,Airplane,Vans,RV 10,0.0,0.0,0.0,1.0,UNKNOWN
5,20191228X23853,2019-12-28,"LAFAYETTE, LA",United States,30.176111,-92.007500,LFT,Fatal(5),Destroyed,Airplane,Piper,PA 31T,5.0,2.0,2.0,0.0,TAKEOFF

In [15]:
# fill NaN Airport codes

df['Airport.Code'].fillna('UNKNOWN', inplace=True)

In [19]:
# fill NaN Aircraft categories

df['Aircraft.Category'].fillna('Unknown', inplace=True)

In [22]:
df['Make'].fillna('Unknown', inplace=True)
df['Model'].fillna('Unknown', inplace=True)

In [24]:
df['Location'].fillna('Unknown', inplace=True)
df['Country'].fillna('Unknown', inplace=True)
df['Injury.Severity'].fillna('Unknown', inplace=True)
df['Aircraft.Damage'].fillna('Unknown', inplace=True)

In [26]:
df.sample(10)

,Event.Id,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Injury.Severity,Aircraft.Damage,Aircraft.Category,Make,Model,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Broad.Phase.of.Flight
26712,20040929X01515,2004-09-23,"Milton, FL",United States,30.645277,-86.998611,2R4,Fatal(4),Destroyed,Unknown,Cessna,R182,4.0,0.0,0.0,0.0,TAKEOFF
3396,20171007X12946,2017-10-07,"Topping, VA",United States,37.588055,-76.474445,W75,Non-Fatal,Substantial,Airplane,MOONEY,M20,0.0,0.0,2.0,1.0,TAKEOFF
1261,20190315X83105,2019-03-15,"Madras, OR",United States,44.670278,-121.155278,S33,Non-Fatal,Substantial,Airplane,Cessna,152,0.0,0.0,0.0,1.0,LANDING
28662,20031001X01642,2003-09-28,"Roche Harbor, WA",United States,48.583611,-123.057222,UNKNOWN,Non-Fatal,Substantial,Unknown,Thompson,Avid Flyer,0.0,0.0,0.0,2.0,CRUISE
15030,20101102X13215,2010-10-25,"Lander, WY",United States,43.161667,-109.560000,UNKNOWN,Fatal(4),Substantial,Airplane,MOONEY,M20J,4.0,0.0,0.0,0.0,UNKNOWN
27776,20040413X00454,2004-04-11,"Denver, CO",United States,39.858611,-104.666945,DEN,Incident,Unknown,Unknown,Canadair,CL-600-2C10,0.0,0.0,0.0,60.0,APPROACH
25902,20050419X00477,2005-03-25,"West Palm Beach, FL",United States,26.683056,-80.095555,KPBI,Non-Fatal,Substantial,Airplane,Piper,PA-23-250,0.0,0.0,0.0,1.0,LANDING
7829,20150205X34400,2015-02-05,"Andrews, TX",United States,32.347222,-102.536666,E11,Non-Fatal,Substantial,Airplane,BEECH,A36,0.0,2.0,2.0,0.0,APPROACH
24291,20060111X00049,2005-12-16,"Stuart, FL",United States,27.180834,-80.221111,KSUA,Non-Fatal,Substantial,Airplane,Cessna,210,0.0,0.0,2.0,0.0,APPROACH
3918,20170707X85152,2017-07-07,"Pine Bluff, AR",United States,34.170278,-91.935277,PBF,Non-Fatal,Substantial,Airplane,CESSNA,170B,0.0,0.0,0.0,3.0,LANDING

In [27]:
df.to_csv('cleaned_data.csv')